export { default as Navbar } from "./Navbar";
export { default as Hero } from "./Hero";
export { default as About } from "./About";
export { default as Skills } from "./Skills";
export { default as Projects } from "./Projects";
export { default as ProjectCard } from "./ProjectCard";
export { default as Experience } from "./Experience";
export { default as Certificate } from "./Certificate";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
export { default as AnimatedSection } from "./AnimatedSection"
export { default as BackgroundDecor } from "./BackgroundDecor"
export { default as SkillCard } from "./SkillCard"
export { default as SkillItem } from "./SkillItem"